version: '3'
services:
  weather_exporter:
    image: weather-exporter
    container_name: weather-exporter
    ports:
      - 9265:9265
    volumes:
      - ./config.json:/etc/weather_exporter/config.json
